### ISSUE TITLE
 Simplifying Repository Structure for Automated Batch Script Setup

### ISSUE THREAD

**Issue by umair-hassan** [chriscline/ExperimentAutomator#2]
**Issue: Simplifying Repository Structure for Automated Batch Script Setup**

**Description:**

Hi Chris,

I wanted to suggest a modification to the repository structure that would make it easier to set up using automated batch scripts.

**Proposed Repository Structure:**

![image](https://github.com/chriscline/ExperimentAutomator/assets/46323919/f3781607-b5a9-4eff-b886-81286e8cbab7)

**Benefits of the Proposed Structure:**

1. **Centralized setup**: By moving all the necessary files and directories to the repository's root, we can create a more centralized setup.
2. **Automated batch script**: For example at: [ExperimentProtocol-TBSiEEG](https://github.com/KellerLab-Stanford/ExperimentProtocol-TBSiEEG). With the new structure, we can create a batch script that automates the setup process, including virtual environment creation and dependency installation.
3. **Improved user experience**: Users will have a smoother onboarding experience, reducing the chance of errors and manual setup steps.

**Next Steps:**

I kindly request your consideration of this proposed modification to enhance the user experience and simplify the setup process. If you find it feasible, I would be more than happy to contribute to implementing these changes.

Best regards,
Umair

**Comment by chriscline** [comment]
Closing since this is not within the scope of this repo, handling separately!
